### ISSUE TITLE
Video 2: You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by theorye** [wesbos/Learn-Redux-Starter-Files#11]
```javascript
// let's go!
import React from 'react';
import { render } from 'react-dom';

// Import CSS
import css from './styles/style.styl';

render(<p>hi</p>, document.getElementById('root'));
```

causes this to happen:
```
ERROR in ./client/reduxstagram.js
Module parse failed: C:\Users\me\documents\React-Redux\learn-redux\client\reduxstagram.js Unexpected token (8:7)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (8:7)
    at Parser.pp.raise (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:923:13)
    at Parser.pp.unexpected (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:1490:8)
    at Parser.pp.parseExprAtom (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:333:12)
    at Parser.pp.parseExprSubscripts (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:228:19)
    at Parser.pp.parseMaybeUnary (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:207:17)
    at Parser.pp.parseExprOps (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:154:19)
    at Parser.pp.parseMaybeConditional (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:136:19)
    at Parser.pp.parseMaybeAssign (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:112:19)
    at Parser.pp.parseExprList (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:660:23)
    at Parser.pp.parseSubscripts (C:\Users\limit\Documents\React-Redux\learn-redux\node_modules\acorn\dist\acorn.js:252:29)
```

This is with a fresh copy of the "learn-redux" folder and fresh npm install.

**Comment by indiesquidge** [comment]
@theorye I'm getting the same error. Looking into it now.

**Comment by indiesquidge** [comment]
Correction, my `reduxstagram.js` file works fine when it appears as you show above. I get the error when I try and import `main.js` and use that component.

```javascript
import React from 'react';
import { render } from 'react-dom';

import css from './styles/style.styl';

import Main from '../components/main';

render(<Main />, document.getElementById('root'));
```

Strange that we are getting this error at different points in time...

**Comment by TroyWorks** [comment]
this may or may not help but I got this from starting the node.js side direct (e.g. node reduxstagram.js) instead of via npm start.

**Comment by indiesquidge** [comment]
Ah, I figured out what my problem was. I accidentally created the `components` directory at the project root rather than inside `client`. The reason this was breaking is because it wasn't being included in the `webpack` loader for `js` filetypes.

```javascript
{
  test: /\.js$/,
  loaders: ['babel'],
  include: path.join(__dirname, 'client')
}
```

That `include` property is the "problem" since it only looks for code in the `client` folder. The solution for me is to either removed that `include` line (startup process takes _slightly_ longer since `webpack` has to traverse the whole project, but not a big deal), or for me to pay close attention to where things are being created 😛
