### ISSUE TITLE
SyntaxError: Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by tokhi** [wesbos/Learn-Redux-Starter-Files#19]
I am getting the error below on `npm start`, however the `.babelrc` is also exist:
```
npm start


> learn-redux@1.0.0 start /vagrant_data/redux/Learn-Redux-Starter-Files/learn-redux0
> node devServer.js

/vagrant_data/redux/Learn-Redux-Starter-Files/learn-redux0/node_modules/webpack/lib/Compilation.js:523


SyntaxError: Unexpected token ILLEGAL
    at Object.exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/vagrant_data/redux/Learn-Redux-Starter-Files/learn-redux0/node_modules/webpack/lib/Compiler.js:8:19)
    at Module._compile (module.js:541:32)

npm ERR! Linux 3.2.0-23-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.2.2
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE
npm ERR! learn-redux@1.0.0 start: `node devServer.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the learn-redux@1.0.0 start script 'node devServer.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the learn-redux package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node devServer.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs learn-redux
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls learn-redux
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /vagrant_data/redux/Learn-Redux-Starter-Files/learn-redux0/npm-debug.log
```

OS and node version:
```
$ node -v
v6.2.2
$ npm -v
3.9.5
Linux precise64 3.2.0-23-generic #36-Ubuntu

```

**Comment by wesbos** [comment]
You likely have a syntax error in one of your files and webpack is breaking. I can't see from this error though

**Comment by tokhi** [comment]
I just cloned the master branch, and I haven't changed anything, thats what I get after `npm start`

**Comment by wesbos** [comment]
Hrm - could you clarify

>  however the .babelrc is also exist:

**Comment by tokhi** [comment]
In the readme file its mentioned:

> Q: I'm getting Unexpected Token Error
> A: You probably don't have the .babelrc file in your learn-redux folder. This makes sure that you have all the right transpile dependencies.

So thats why I wrote the `.babelrc` file is also exist...
